#' Execute a given blast command
#'
#' @param command The blast command to be run
#' @param output The output file to store the blast results in
#' 
#' @return The output file generated by the blastn call
#' @export

blast <- function(command, output){
  if(!file.exists(output)){ # If output file doesn't exist we create it
    file.create(output)
  }
  
  try(system(command)) # Perform the blast command
  
  return(output)
}